---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando el servicio
      shell: |
        echo "Desplegando Frontend Service"
        /opt/sinpad/qa/scripts/deployfrontendservice.sh
