---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando el servicio
      shell: |
        echo "Desplegando Sectorial Service"
        /opt/sinpad/qa/scripts/deploysectservice.sh
